spring:
  rabbitmq:
    host: 172.162.15.111
    username: admin
    password: admin
    virtual-host: topicFile
    publisher-confirms: true    #开启发送确认
    publisher-returns: true     #开启发送失败退回
    listener:
      simple:
        acknowledge-mode: manual  #开启ACK
  datasource:
    url: jdbc:mysql://172.162.15.113:3306/david?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: db_user
    password: 2wsx3edcZSE
    driver-class-name: com.mysql.jdbc.Driver