spring:
  rabbitmq:
    host: 172.162.15.111
    username: admin
    password: admin
    virtual-host: topicFile
    publisher-confirms: true    #开启发送确认
    publish er-returns: true     #开启发送失败退回
    listener:
      simple:
        acknowledge-mode: manual  #开启ACK
        default-requeue-rejected: false #被拒绝的消息进入到死信队列
        retry:
          enabled: true #开启消息消费失败重试
          max-attempts: 5 #消息消费失败后最多重复消息5次
          initial-interval: 2000 #间隔1秒时间重新消费失败消息
  datasource:
    url: jdbc:mysql://172.162.15.113:3306/coupon?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&autoReconnect=true&autoReconnectForPools=true&useSSL=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    sql-script-encoding: UTF-8
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat,slf4j,wall
    maxActive: 200
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    useGlobalDataSourceStat: true
    logSlowSql: true
  redis:
   # host: 127.0.0.1
   # password: redis
   # port: 6379
    timeout: 1000

    lettuce:
      pool:
        max-active: 20
        max-wait: 5000
        max-idle: 15
        min-idle: 5
    sentinel:
      master: mymaster
      nodes: 127.0.0.1:56379,127.0.0.1:56380,127.0.0.1:56381
